# Site settings
title: Acrogenesis Blog
email: adrian.rangel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bleeding Edge Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acrogenesis.com" # the base hostname & protocol for your site
twitter_username: acrogenesis
github_username:  acrogenesis

# Build settings
markdown: kramdown

# Outputting
permalink: pretty
timezone: Monterrey

# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"

author:
  name: Adrian Rangel
  email: adrian.rangel@gmail.com
  github: acrogenesis
  twitter: acrogenesis
  bio: Bleeding Edge Developer.
  email_md5: 4d574942e2627e5a01262657dda8a299

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
