# Site settings
title: Acrogenesis Blog
email: adrian.rangel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bleeding Edge Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://acrogenesis.com" # the base hostname & protocol for your site
twitter_username: acrogenesis
github_username:  acrogenesis

# Build settings
markdown: kramdown

# Outputting
permalink: /:title
timezone: Monterrey
paginate: 5
highlighter: pygments
